workflows:
  default:
    name: iOS Release Build

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build ios --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: api_key
  ``