workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build iOS (Flutter)
        script: flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
